### ISSUE TITLE
Cannot install package: CUDA Error - Fall back option to CPU

### ISSUE THREAD

**Issue by StatMixedML** [dsgibbons/shap#49] opened 2023-05-18 17:08 UTC
Dear community,

Thanks for maintaining the shap-package.

Having installed CUDA-11.7 and using `pip install git+https://github.com/dsgibbons/shap.git` throws the following error. Can you add a CPU fallback option to the `setup.py`.

```python

```

**Comment by dsgibbons** [comment] 2023-05-18 19:20
Duplicate of #50

**Closed** 2023-05-18 19:20 UTC
